# NOTE: the values in this secret are provided as working manifest example and are not the values
# used during an install. New values will be generated as part of `argocd install`
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # bcrypt hash of the string "password"
  admin.password: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
  # random server signature key for session validation
  server.secretkey: aEDvv73vv70F77+9CRBSNu+/vTYQ77+9EUFh77+9LzFyJ++/vXfLsO+/vWRbeu+/ve+/vQ==

  # these keys hold the shared secret for authenticating GitHub/GitLab webhook events
  github.webhook.secret: shhhh! it's a github secret
  gitlab.webhook.secret: shhhh! it's a gitlab secret
  bitbucket.webhook.uuid: your-bitbucket-uuid

  # the following of user defined keys which are referenced in the example argocd-cm configmap
  # as pat of SSO configuration.
  dex.github.clientSecret: nv1vx8w4gw5byrflujfkxww6ykh85yq818aorvwy
  dex.acme.clientSecret: 5pp7dyre3d5nyk0ree1tr0gd68k18xn94x8lfae9
  dex.okta.clientSecret: x41ztv6ufyf07oyoopc6f62p222c00mox2ciquvt
