required = [
  "github.com/gogo/protobuf/protoc-gen-gofast",
  "github.com/gogo/protobuf/protoc-gen-gogofast",
  "golang.org/x/sync/errgroup",
  "k8s.io/code-generator/cmd/go-to-protobuf",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/tools/cmd/cover",
  "github.com/argoproj/pkg/time",
]

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "v1.3.1"

# override argo outdated dependency
[[override]]
  branch = "release-1.10"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.10"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/code-generator"

[[override]]
  branch = "release-7.0"
  name = "k8s.io/client-go"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/ksonnet/ksonnet"
  version = "v0.11.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "v1.11.0"

# override ksonnet's logrus dependency
[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "ea8897e79973357ba785ac2533559a6297e83c44"
