extra:
  analytics:
    property: G-5Z1VTPDL73
    provider: google
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
markdown_extensions:
- markdown_include.include
- codehilite:
    css_class: highlight
- admonition
- toc:
    permalink: true
- pymdownx.superfences
nav:
- Overview: index.md
- understand_the_basics.md
- core_concepts.md
- getting_started.md
- Operator Manual:
  - operator-manual/index.md
  - operator-manual/architecture.md
  - operator-manual/installation.md
  - operator-manual/core.md
  - operator-manual/declarative-setup.md
  - operator-manual/app-any-namespace.md
  - operator-manual/ingress.md
  - High Availability:
    - Overview: operator-manual/high_availability.md
    - Dynamic Cluster Distribution: operator-manual/dynamic-cluster-distribution.md
  - User Management:
    - operator-manual/user-management/index.md
    - operator-manual/user-management/auth0.md
    - operator-manual/user-management/microsoft.md
    - operator-manual/user-management/okta.md
    - operator-manual/user-management/onelogin.md
    - operator-manual/user-management/keycloak.md
    - operator-manual/user-management/openunison.md
    - operator-manual/user-management/google.md
    - operator-manual/user-management/zitadel.md
    - operator-manual/user-management/identity-center.md
    - operator-manual/rbac.md
  - Security:
    - Overview: operator-manual/security.md
    - snyk/index.md
    - operator-manual/signed-release-assets.md
  - operator-manual/tls.md
  - operator-manual/cluster-management.md
  - operator-manual/cluster-bootstrapping.md
  - operator-manual/secret-management.md
  - operator-manual/disaster_recovery.md
  - operator-manual/reconcile.md
  - operator-manual/webhook.md
  - operator-manual/health.md
  - operator-manual/resource_actions.md
  - operator-manual/custom_tools.md
  - operator-manual/custom-styles.md
  - operator-manual/ui-customization.md
  - operator-manual/metrics.md
  - operator-manual/web_based_terminal.md
  - operator-manual/config-management-plugins.md
  - operator-manual/deep_links.md
  - Notifications:
    - Overview: operator-manual/notifications/index.md
    - operator-manual/notifications/triggers.md
    - operator-manual/notifications/templates.md
    - operator-manual/notifications/functions.md
    - operator-manual/notifications/catalog.md
    - operator-manual/notifications/monitoring.md
    - operator-manual/notifications/subscriptions.md
    - operator-manual/notifications/troubleshooting.md
    - operator-manual/notifications/troubleshooting-commands.md
    - operator-manual/notifications/troubleshooting-errors.md
    - Notification Services:
      - operator-manual/notifications/services/alertmanager.md
      - operator-manual/notifications/services/awssqs.md
      - operator-manual/notifications/services/email.md
      - operator-manual/notifications/services/github.md
      - operator-manual/notifications/services/googlechat.md
      - operator-manual/notifications/services/grafana.md
      - operator-manual/notifications/services/mattermost.md
      - operator-manual/notifications/services/newrelic.md
      - operator-manual/notifications/services/opsgenie.md
      - operator-manual/notifications/services/overview.md
      - operator-manual/notifications/services/pagerduty.md
      - operator-manual/notifications/services/pagerduty_v2.md
      - operator-manual/notifications/services/pushover.md
      - operator-manual/notifications/services/rocketchat.md
      - operator-manual/notifications/services/slack.md
      - operator-manual/notifications/services/teams.md
      - operator-manual/notifications/services/telegram.md
      - operator-manual/notifications/services/webex.md
      - operator-manual/notifications/services/webhook.md
  - operator-manual/troubleshooting.md
  - ApplicationSet:
    - Introduction: operator-manual/applicationset/index.md
    - Installations: operator-manual/applicationset/Getting-Started.md
    - Use Cases: operator-manual/applicationset/Use-Cases.md
    - Security: operator-manual/applicationset/Security.md
    - How ApplicationSet controller interacts with Argo CD: operator-manual/applicationset/Argo-CD-Integration.md
    - Generators:
      - operator-manual/applicationset/Generators.md
      - operator-manual/applicationset/Generators-List.md
      - operator-manual/applicationset/Generators-Cluster.md
      - operator-manual/applicationset/Generators-Git.md
      - operator-manual/applicationset/Generators-Matrix.md
      - operator-manual/applicationset/Generators-Merge.md
      - operator-manual/applicationset/Generators-SCM-Provider.md
      - operator-manual/applicationset/Generators-Cluster-Decision-Resource.md
      - operator-manual/applicationset/Generators-Pull-Request.md
      - operator-manual/applicationset/Generators-Post-Selector.md
      - operator-manual/applicationset/Generators-Plugin.md
    - Template fields:
      - operator-manual/applicationset/Template.md
      - operator-manual/applicationset/GoTemplate.md
    - Controlling Resource Modification: operator-manual/applicationset/Controlling-Resource-Modification.md
    - Application Pruning & Resource Deletion: operator-manual/applicationset/Application-Deletion.md
    - Progressive Syncs: operator-manual/applicationset/Progressive-Syncs.md
    - Git File Generator Globbing: operator-manual/applicationset/Generators-Git-File-Globbing.md
    - ApplicationSet Specification Reference: operator-manual/applicationset/applicationset-specification.md
    - ApplicationSet in any namespace: operator-manual/applicationset/Appset-Any-Namespace.md
  - Server Configuration Parameters:
    - operator-manual/server-commands/argocd-server.md
    - operator-manual/server-commands/argocd-application-controller.md
    - operator-manual/server-commands/argocd-repo-server.md
    - operator-manual/server-commands/argocd-dex.md
    - operator-manual/server-commands/additional-configuration-method.md
  - Upgrading:
    - operator-manual/upgrading/overview.md
    - operator-manual/upgrading/2.12-2.13.md
    - operator-manual/upgrading/2.11-2.12.md
    - operator-manual/upgrading/2.10-2.11.md
    - operator-manual/upgrading/2.9-2.10.md
    - operator-manual/upgrading/2.8-2.9.md
    - operator-manual/upgrading/2.7-2.8.md
    - operator-manual/upgrading/2.6-2.7.md
    - operator-manual/upgrading/2.5-2.6.md
    - operator-manual/upgrading/2.4-2.5.md
    - operator-manual/upgrading/2.3-2.4.md
    - operator-manual/upgrading/2.2-2.3.md
    - operator-manual/upgrading/2.1-2.2.md
    - operator-manual/upgrading/2.0-2.1.md
    - operator-manual/upgrading/1.8-2.0.md
    - operator-manual/upgrading/1.7-1.8.md
    - operator-manual/upgrading/1.6-1.7.md
    - operator-manual/upgrading/1.5-1.6.md
    - operator-manual/upgrading/1.4-1.5.md
    - operator-manual/upgrading/1.3-1.4.md
    - operator-manual/upgrading/1.2-1.3.md
    - operator-manual/upgrading/1.1-1.2.md
    - operator-manual/upgrading/1.0-1.1.md
  - Project Specification Reference: operator-manual/project-specification.md
- User Guide:
  - user-guide/index.md
  - user-guide/application_sources.md
  - user-guide/kustomize.md
  - user-guide/helm.md
  - user-guide/import.md
  - user-guide/jsonnet.md
  - user-guide/directory.md
  - user-guide/tool_detection.md
  - user-guide/projects.md
  - user-guide/private-repositories.md
  - user-guide/multiple_sources.md
  - GnuPG verification: user-guide/gpg-verification.md
  - user-guide/auto_sync.md
  - Diffing:
    - Diff Strategies: user-guide/diff-strategies.md
    - Diff Customization: user-guide/diffing.md
  - user-guide/orphaned-resources.md
  - user-guide/compare-options.md
  - user-guide/sync-options.md
  - user-guide/parameters.md
  - user-guide/environment-variables.md
  - user-guide/build-environment.md
  - user-guide/tracking_strategies.md
  - user-guide/resource_tracking.md
  - user-guide/resource_hooks.md
  - user-guide/selective_sync.md
  - user-guide/sync-waves.md
  - user-guide/sync_windows.md
  - user-guide/sync-kubectl.md
  - user-guide/skip_reconcile.md
  - Generating Applications with ApplicationSet: user-guide/application-set.md
  - user-guide/ci_automation.md
  - user-guide/app_deletion.md
  - user-guide/best_practices.md
  - user-guide/status-badge.md
  - user-guide/external-url.md
  - user-guide/extra_info.md
  - Notification subscriptions: user-guide/subscriptions.md
  - user-guide/annotations-and-labels.md
  - Command Reference: user-guide/commands/argocd.md
  - Application Specification Reference: user-guide/application-specification.md
- Developer Guide:
  - developer-guide/index.md
  - Architecture:
    - developer-guide/architecture/authz-authn.md
    - developer-guide/architecture/components.md
  - Code Contribution Guide: developer-guide/code-contributions.md
  - Toolchain Guide: developer-guide/toolchain-guide.md
  - developer-guide/contributors-quickstart.md
  - developer-guide/release-process-and-cadence.md
  - developer-guide/running-locally.md
  - developer-guide/debugging-remote-environment.md
  - developer-guide/use-gitpod.md
  - developer-guide/api-docs.md
  - developer-guide/test-e2e.md
  - developer-guide/dependencies.md
  - developer-guide/ci.md
  - developer-guide/releasing.md
  - developer-guide/docs-site.md
  - developer-guide/static-code-analysis.md
  - Extensions:
    - developer-guide/extensions/ui-extensions.md
    - developer-guide/extensions/proxy-extensions.md
  - developer-guide/faq.md
- faq.md
- security_considerations.md
- Support: SUPPORT.md
- roadmap.md
- Releases ⧉: https://github.com/argoproj/argo-cd/releases
- Blog ⧉: https://blog.argoproj.io/
repo_url: https://github.com/argoproj/argo-cd
site_name: Argo CD - Declarative GitOps CD for Kubernetes
site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true
theme:
  custom_dir: overrides
  favicon: assets/favicon.png
  font:
    text: Work Sans
  logo: assets/logo.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
