site_name: Argo CD - Declarative GitOps CD for Kubernetes
repo_url: https://github.com/argoproj/argo-cd
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.png'
  custom_dir: overrides
extra_javascript:
- assets/versions.js
extra_css:
- assets/versions.css
google_analytics:
- 'UA-105170809-2'
- 'auto'

markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Overview: index.md
  - Concepts & Terminology: basics/terminology.md
  - Getting started: 
    - Server installation: getting_started/install.md
    - CLI installation: getting_started/install_cli.md
    - First steps: getting_started/first_steps.md
  - Basics:
    - Applications: 
      - Overview: basics/apps/index.md
      - Source: basics/apps/source.md
      - Destination: basics/apps/destination.md
      - State: basics/apps/state.md
      - Managing Applications: basics/apps/manage.md
      - Overriding Parameters: basics/apps/overrides.md
    - Clusters:
      - Overview: basics/clusters/index.md
      - Internal: basics/clusters/internal.md
      - External clusters: basics/clusters/external.md
      - Managing clusters: basics/clusters/manage.md
    - Repositories: 
      - Overview: basics/repos/index.md
      - Authentication: basics/repos/auth.md
      - Managing Repositories: basics/repos/manage.md 
      - Repos: basics/repositories.md
    - Projects: 
      - Overview: basics/projects/index.md
      - Settings: basics/projects/settings.md
      - Roles: basics/projects/roles.md
  - Syncing:
    - Overview: syncing/index.md
    - Sync states: syncing/states.md
    - Sync policy: syncing/policy.md
    - Sync options: syncing/options.md
    - Sync phases/waves: syncing/waves.md
    - Sync windows: syncing/windows.md
    - Tracking strategies: syncing/tracking.md
    - Application health: syncing/health.md
    - Diffing behavior: syncing/diffing.md
    - GnuPG commit verification: syncing/gnupg.md
    - Git refresh webhooks: syncing/git_webhooks.md
  - Tools:
    - Overview: tools/index.md
    - Helm: tools/helm.md
    - Kustomize: tools/kustomize.md
    - JSonnet: tools/jsonnet.md
    - Third-party tools: tools/plugins.md
  - Access control & RBAC:
    - Overview: rbac/index.md
  - Operations & Maintenance:
    - Architectural Overview: operations/index.md
    - Backup & Restore: operations/backup_restore.md
    - Scaling Up: operations/scaling.md
    - Metrics: operations/metrics.md
    - Ingress configuration:
      - Overview: operations/ingress/index.md
      - Ambassador: operations/ingress/ambassador.md
      - AWS ALB and ELB: operations/ingress/aws.md
      - Contour: operations/ingress/contour.md
      - Nginx: operations/ingress/nginx.md
      - Traefik: operations/ingress/traefik.md
    - Local users: operations/users.md
    - Security: operations/security.md
    - Single Sign On (SSO): operations/sso/overview.md
    - Upgrading:
      - Upgrading Argo CD: operations/upgrading/index.md
      - Upgrade guides:
        - 1.7 to 1.8: operations/upgrading/1_7-1_8.md
        - 1.6 to 1.7: operations/upgrading/1_6-1_7.md
        - 1.5 to 1.6: operations/upgrading/1_5-1_6.md
        - 1.4 to 1.5: operations/upgrading/1_4-1_5.md
        - 1.3 to 1.4: operations/upgrading/1_3-1_4.md
        - 1.2 to 1.3: operations/upgrading/1_2-1_3.md
        - 1.1 to 1.2: operations/upgrading/1_1-1_2.md
  - Troubleshooting:
    - Performance: troubleshooting/performance.md
    - Common Issues: troubleshooting/common-issues.md
  - Reference:
    - Custom Resource Definitions:
      - Application CRD: reference/crd/application.md
      - AppProject CRD: reference/crd/appproject.md
    - Configuration:
      - argocd-cm: reference/config/argocd-cm.md
      - argocd-secret: reference/config/argocd-secret.md
      - argocd-ssh-known-hosts-cm: reference/config/argocd-ssh-known-hosts-cm.md
      - argocd-tls-certs-cm: reference/config/argocd-tls-certs-cm.md
      - argocd-gpg-keys-cm: reference/config/argocd-gpg-keys-cm.md
      - cluster-secret: reference/config/cluster-secret.md
    - CLI usage:
      - argocd: reference/cli/argocd.md
      - argocd-util: reference/cli/argocd-util.md
    - Server workload parametrization:
      - argocd-server: reference/server/argocd-server.md
      - argocd-repo-server: reference/server/argocd-repo-server.md
      - argocd-application-controller: reference/server/argocd-application-controller.md
  - FAQ: faq.md
  - Community: community.md
  - Releases ⧉: https://github.com/argoproj/argo-cd/releases
  - Blog ⧉: https://blog.argoproj.io/
