site_name: Argo CD - Declarative GitOps CD for Kubernetes
repo_url: https://github.com/argoproj/argo-cd
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
google_analytics:
- 'UA-105170809-2'
- 'auto'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Overview: index.md
  - understand_the_basics.md
  - core_concepts.md
  - getting_started.md
  - Operator Manual:
    - operator-manual/index.md
    - operator-manual/architecture.md
    - operator-manual/declarative-setup.md
    - operator-manual/ingress.md
    - Single Sign On (SSO) & Role-Based Access Control (RBAC):
      - operator-manual/sso/index.md
      - operator-manual/sso/auth0.md
      - operator-manual/sso/microsoft.md
      - operator-manual/sso/okta.md
      - operator-manual/sso/onelogin.md
      - operator-manual/rbac.md
    - operator-manual/security.md
    - operator-manual/cluster-bootstrapping.md
    - operator-manual/secret-management.md
    - operator-manual/high_availability.md
    - operator-manual/disaster_recovery.md
    - operator-manual/webhook.md
    - operator-manual/health.md
    - operator-manual/custom_tools.md
    - operator-manual/metrics.md
  - User Guide:
    - user-guide/index.md
    - user-guide/application_sources.md
    - user-guide/kustomize.md
    - user-guide/helm.md
    - user-guide/ksonnet.md
    - user-guide/jsonnet.md
    - user-guide/config-management-plugins.md
    - user-guide/tool_detection.md
    - user-guide/projects.md
    - user-guide/private-repositories.md
    - user-guide/auto_sync.md
    - user-guide/diffing.md
    - user-guide/orphaned-resources.md
    - user-guide/compare-options.md
    - user-guide/sync-options.md
    - user-guide/parameters.md
    - user-guide/build-environment.md
    - user-guide/tracking_strategies.md
    - user-guide/resource_hooks.md
    - user-guide/selective_sync.md
    - user-guide/sync-waves.md
    - user-guide/sync_windows.md
    - user-guide/ci_automation.md
    - user-guide/app_deletion.md
    - user-guide/best_practices.md
    - user-guide/status-badge.md
  - Developer Guide:
    - developer-guide/index.md
    - CONTRIBUTING.md
    - developer-guide/api-docs.md
    - developer-guide/test-e2e.md
    - developer-guide/ci.md
    - developer-guide/releasing.md
    - developer-guide/site.md
  - faq.md
  - Support: SUPPORT.md
  - Releases ⧉: https://github.com/argoproj/argo-cd/releases
  - Roadmap ⧉: https://github.com/argoproj/argo-cd/milestones
  - Blog ⧉: https://blog.argoproj.io/
