apiVersion: v1
kind: Service
metadata:
  name: dex-server
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5556
    targetPort: 5556
  - name: grpc
    protocol: TCP
    port: 5557
    targetPort: 5557
