apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-server
spec:
  template:
    spec:
      serviceAccountName: dex-server
      initContainers:
      - name: copyutil
        image: argoproj/argocd:latest
        imagePullPolicy: Always
        command: [cp, /usr/local/bin/argocd-util, /shared]
        volumeMounts:
        - mountPath: /shared
          name: static-files
      containers:
      - name: dex
        image: quay.io/dexidp/dex:v2.12.0
        imagePullPolicy: Always
        command: [/shared/argocd-util, rundex]
        ports:
        - containerPort: 5556
        - containerPort: 5557
        volumeMounts:
        - mountPath: /shared
          name: static-files
      volumes:
      - emptyDir: {}
        name: static-files
