apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-cm.yaml
- argocd-secret.yaml
- argocd-rbac-cm.yaml
- argocd-ssh-known-hosts-cm.yaml
- argocd-tls-certs-cm.yaml
- argocd-gpg-keys-cm.yaml
