---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-server
spec:
  selector:
    matchLabels:
      app: dex-server
  template:
    metadata:
      labels:
        app: dex-server
    spec:
      serviceAccountName: argocd-server
      initContainers:
      - name: copyutil
        image: argoproj/argocd-server:v0.8.0
        command: [cp, /argocd-util, /shared]
        volumeMounts:
        - mountPath: /shared
          name: static-files
      containers:
      - name: dex
        image: quay.io/coreos/dex:v2.10.0
        command: [/shared/argocd-util, rundex]
        ports:
          - containerPort: 5554
          # - containerPort: 5555
          - containerPort: 5556
          # - containerPort: 5557
        volumeMounts:
        - mountPath: /shared
          name: static-files
      volumes:
      - emptyDir: {}
        name: static-files
