apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- overlays/argocd-repo-server-deployment.yaml
- overlays/argocd-server-deployment.yaml
- overlays/argocd-application-controller-statefulset.yaml

images:
- name: quay.io/argoproj/argocd
  newName: quay.io/codefresh/argocd
  newTag: v2.5.5-cap-CR-verify-aud-claim
resources:
- ../../base/application-controller
- ../../base/applicationset-controller
- ../../base/dex
- ../../base/repo-server
- ../../base/server
- ../../base/config
- ./redis-ha
