apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/application-controller
- ../../base/dex
- ../../base/repo-server
- ../../base/server
- ../../base/config
- ./redis-ha

patchesStrategicMerge:
- overlays/argocd-repo-server-deployment.yaml
- overlays/argocd-server-deployment.yaml
- overlays/argocd-application-controller-deployment.yaml

images:
- name: argoproj/argocd
  newName: argoproj/argocd
  newTag: v1.1.0-rc2
- name: argoproj/argocd-ui
  newName: argoproj/argocd-ui
  newTag: v1.1.0-rc2
