name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2.1.2
        with:
          go-version: '1.13.6'
      - run: make test
      - uses: actions-contrib/golangci-lint@v1
        with:
          args: run --timeout=5m
        env:
          GOROOT: ""
      - uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage.out
