name: Codegen PR
on:
  workflow_dispatch:
  push:
    branches:
      - 'codegen-painkiller'

jobs:
  codegen:
    name: Check changes to generated code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - name: Codegen
        # uses: ./.github/workflows/actions/codegen
        uses: ./.github/workflows/actions/hello
      - run: |
          git config --global user.email 'ci@argoproj.com'
          git config --global user.name 'CI'
          git add .
          git commit -m "Run codegen"
          CODEGEN_BRANCH=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-codegen
          git checkout -b $CODEGEN_BRANCH
          git remote add bot "https://$TOKEN@github.com/argo-bot/argo-cd"
          git push bot $CODEGEN_BRANCH --force
        working-directory: /home/runner/go/src/github.com/argoproj/argo-cd
        env:
          TOKEN: ${{ secrets.TOKEN }}
