apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: argocd-conversion-webhook
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: conversion-webhook
  name: argocd-conversion-webhook
