apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-conversion-webhook-deployment.yaml
- argocd-conversion-webhook-service.yaml
- argocd-conversion-webhook-sa.yaml
- argocd-conversion-webhook-clusterrole.yaml
- argocd-conversion-webhook-clusterrolebinding.yaml
